### ISSUE TITLE
白宮聯署 WH Petitions on Covid-19 SARI

### ISSUE THREAD

**Issue by theagora** [agorahub/_meta#2]
[START FROM](https://petitions.whitehouse.gov/petition/create) - We the People ask the federal government to: 
- [ ] a. Take or explain a position on an issue or policy. 
- [ ] b. Tell us what the federal government is doing about an issue. 
- [ ] c. Change an existing Administration policy. 
- [ ] d. Propose a new Administration policy. 
- [ ] e. Call on Congress to act on an issue. 

Please check and update the [List of Proposals](https://github.com/agorahub/_meta/blob/agoran/theagora/sari/wh_petitions.md).

- [x] P1: https://petitions.whitehouse.gov/petition/call-permit-generic-drug-remdesivir-urgent-medical-care-early-infected-2019-ncov-sari-asia (2020.02.07+30D)
- [x] P2: https://petitions.whitehouse.gov/petition/urge-china-government-disclose-adequate-information-and-offer-fair-medication-infected-patients-covid-19 (2020.02.14+30D)

**Comment by theagora** [comment]
- [x] a. Take or explain a position on an issue or policy.

**Title**: Call for Permit of Generic Drug of Remdesivir for Urgent Medical Care to the Early Infected of 2019-nCoV SARI in Asia

**Description**: As per 2019-nCoV epidemic has been spreading fast with a worldwide momentum but no evidence tells it will stop in the month-counted future. We strongly suggest the federal government to coordinate the ongoing process of clinical trial on the early infected but NOT ONLY the heavily-injured patients, AND permit the test of generic drug for the Remdesivir. Here are the reasons: 1) Huge number of early infected are NOT counted in the reporting system, and they will SOON become seriously infected due to lack of proper treatment. 2) It could be a convincing model for a for-profit organization to cooperate with sovereigns for long-time strategies but NOT ONLY take defensive actions against patent squatting in PHEIC incidents.

**Petition URL**: https://petitions.whitehouse.gov/petition/call-permit-generic-drug-remdesivir-urgent-medical-care-early-infected-2019-ncov-sari-asia

**Target**: 100,000 online signs 
**Period**: 7 Feb ~ 8 Mar, 2020

**Comment by leixiling** [comment]
d.Propose a new Administration policy.
呼吁政府对武汉还建房的小区采取规范的管理措施，目前武汉大量的还建小区物业在前期对疫情不重视，管理松懈。导致最近出现大量的感染者，并且疫情还在逐渐加重。
同时，对于出现疫情的小区，由于闭市，得不到物资供应，人群只能集中去更远的超市购买物资，这导致在超市购物的人群和员工互相交叉感染，疫情进一步蔓延，目前已有消息证实上述所说的正在成为现实。

**Comment by leixiling** [comment]
a. Take or explain a position on an issue or policy.
希望在武汉的新药（克立芝或remdesiver）的施行信息能透明，公布施用状况、对症人群、定点医院等信息，保障用药的公正、公平

**Comment by stevenhoosh** [comment]
统计1月至疫情结束所有死亡人员，并与之前年份相比较，从统计数字上弄清，这次疫情，武汉甚至湖北究竟因此死了多少人！

**Comment by zlf19820410** [comment]
1.请求美国开放克力芝和瑞德西韦两款专利的仿制药授权给中国，直到大规模疫情结束，或提供廉价的这两款药物帮助中国控制疫情，以避免全球陷入危机
2.请美国公司如吉利德等在协助中国进行临床试验以及提供药物的过程中，监督药物使用的公平性，特别请美国援华专家团队监督在武汉，湖北等疫情危重灾区的共平施药问题，尤其是针对大量轻症患者的施药问题
3.召集全球华人感谢吉利德等药物研发企业对此次防疫的巨大贡献，向全球华人宣传吉利德公司对中国防治乙肝、艾滋、丙肝等恶性传染病做出的突出成就，并设立基金，募资酬谢吉利德的研发投入

**Comment by stevenhoosh** [comment]
关于确诊金标准的试剂盒：根据《人物》杂志1月23日报道，辉睿已经向各地供应了五、六万人份的试剂盒，而捷诺在1月16日时就已生产了可供七万五千人份使用的试剂盒。二者加起来能测试十多万人。
而根据南方都市的报道，截至2月5日全湖北省总共检测样本89600多份，其中2月5日检测12277份，2月3、4、5三天（或4、5、6）每天检测数量都超过1万例，则2月2日之前检测量仅有4万例左右，共18天，平均每天不到2200例。
在1月16日至2月2日期间，确诊所使用的试剂盒，产量和用量的巨大差异由什么造成的，应该由谁负责！
请政府公开从有确诊标准以来，每天试剂盒测试用量！

**Comment by theagora** [comment]
> a. Take or explain a position on an issue or policy.
> 希望在武汉的新药（克立芝或remdesiver）的施行信息能透明，公布施用状况、对症人群、定点医院等信息，保障用药的公正、公平

Attn: @leixiling @stevenhoosh 
Ref: [List of Proposals](https://github.com/agorahub/_meta/blob/agoran/theagora/sari/wh_petitions.md)

- [x] a. Take or explain a position on an issue or policy.

**Title**: Urge China Government to Disclose Adequate Information and Offer Fair Medication to the Infected Patients of Covid-19

**Description**: The global outbreak of the Covid-19 (a.k.a. SARI or SARS-CoV-2) has been developing rapidly within communities. And the delayedly-announced PHEIC will last for several months according to research model and updated data, much longer than the propagated. In order to gather sufficient decision making support, we the world require the transparency of information from the source to - including but not limited to - 1) Release medication information of Kriging and/or Remdesivir in terms of symptomatic groups, dosages, and designated hospitals; 2) Employ comparable analysis to amend the statistics data of deaths; and 3) Explain the disproportionately small number of testing cases before 2/2/2020, in contrast to the suppliers' data and the tests after that day.

**Petition URL**: https://petitions.whitehouse.gov/petition/urge-china-government-disclose-adequate-information-and-offer-fair-medication-infected-patients-covid-19

**Target**: 100,000 online signs 
**Period**: 14 Feb ~ 15 Mar, 2020
